name: Publish

on:
  workflow_dispatch:
  push:
    branches:
    - API-Creation

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      
      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '6.0.x'
  
      - name: Restore
        run: sotnet restore .\API_Students
  
      - name: Build
        run: dotnet build ./API_Students/API_Students.sln --configuration Release --no-restore
  
      - name: Publish
        run: dotnet publish ./API_Students/API_Students.sln --configuration Release --no-restore
    
